plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alisinan.minicalc'
    compileSdk 34
    defaultConfig {
        applicationId 'com.alisinan.minicalc'
        minSdk 23
        targetSdk 34
        versionCode 3
        versionName '1.2'
        resourceConfigurations += ['en']
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    packaging {
        resources {
            excludes += ['META-INF/**', 'DebugProbesKt.bin',
                         'kotlin/**', '**/*.kotlin_builtins', '**/*.kotlin_metadata']
        }
    }
}

dependencies {
}